### PR TITLE
Changed formatVariable function

### PR DESCRIPTION
**Pull request by emidblol**
Originally, it would try to lowercase a number. This causes an error. I have (tried) to fix this. I hope it works

### CODE REVIEW

**Comment by emidblol** [comment]
to fix #56 and #57

**Comment by emidblol** [comment]
I mean #58 sorry I'm dumb

**Review by Androz2091 — CHANGES_REQUESTED** [review]
Doesn't work.

**Comment by Androz2091** [comment]
you can't use typeof string =, you need a comparison

**Comment by emidblol** [comment]
Closed because S4D was using the wrong function and I thought it was an error in the package.

**Pull request closed without merging**
